services:
  jekyll:
    image: "${DOCKERHUB_USERNAME}/${ARTIFACT_NAME}:${ENVIRONMENT}-latest"
    build:
      context: ./jekyll
      dockerfile: Dockerfile
    container_name: jekyll-site
    volumes:
      - ./jekyll:/srv/jekyll
    labels:
      - "traefik.enable=true"
      # HTTP router configuration (always present)
      - "traefik.http.routers.jekyll.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.jekyll.entrypoints=web"
      # Conditional labels for HTTPS (only added when DISABLE_HTTPS is not true)
      - "traefik.http.routers.jekyll-ssl.rule=Host(`${DOMAIN}`)${DISABLE_HTTPS:-}"
      - "traefik.http.routers.jekyll-ssl.entrypoints=websecure${DISABLE_HTTPS:-}"
      - "traefik.http.routers.jekyll-ssl.tls.certresolver=myresolver${DISABLE_HTTPS:-}"
      # Service configuration
      - "traefik.http.services.jekyll.loadbalancer.server.port=4000"  
    networks:
      - web

  traefik:
    image: traefik:v2.10
    restart: always
    container_name: traefik-${ENVIRONMENT}
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
      - "${SECURE_PORT}:${SECURE_PORT}"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik/traefik.yml:/etc/traefik/traefik.yml"
      - "./traefik/acme.json:/acme.json"
    networks:
      - web

networks:
  web:
    driver: bridge
