services:
  jekyll-staging:
    image: "${DOCKERHUB_USERNAME}/${ARTIFACT_NAME}:${ENVIRONMENT}-latest"
    container_name: jekyll-staging
    restart: always
    ports:
      - "4001:4000"
    env_file:
      - .env   
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jekyll-staging.rule=Host(`staging.${DOMAIN}`)"
      - "traefik.http.routers.jekyll-staging.entrypoints=web"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      - "traefik.http.routers.jekyll-staging.middlewares=redirect-to-https@docker"
      - "traefik.http.routers.acme-challenge.rule=PathPrefix(`/.well-known/acme-challenge/`)"
      - "traefik.http.routers.acme-challenge.entrypoints=web"
      - "traefik.http.routers.acme-challenge.priority=100"
      - "traefik.http.routers.jekyll-staging-ssl.rule=Host(`staging.${DOMAIN}`)"
      - "traefik.http.routers.jekyll-staging-ssl.entrypoints=websecure"
      - "traefik.http.routers.jekyll-staging-ssl.tls.certresolver=myresolver"
      - "traefik.http.services.jekyll-staging.loadbalancer.server.port=4000"
    networks:
      - traefik_network

networks:
  traefik_network:
    name: traefik_network
    external: true
