services:
  traefik-proxy:
    image: traefik:v2.11
    container_name: traefik-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8080:8080  # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik/traefik.yml:/etc/traefik/traefik.yml"
      - "./traefik/acme.json:/acme.json"
      - "./traefik/logs:/var/log/traefik"       
    env_file:
      - .env      
    labels:
      - "traefik.enable=true"
      # Dashboard access
      - "traefik.http.routers.api.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
      - "traefik.http.routers.api.middlewares=auth"
      # Allow ACME HTTP Challenge
      - "traefik.http.routers.acme-http-solver.rule=PathPrefix(`/.well-known/acme-challenge/`)"
      - "traefik.http.routers.acme-http-solver.entrypoints=web"
      - "traefik.http.routers.acme-http-solver.priority=100"
      # Middleware for basic auth
      - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_DASHBOARD_USERS}"
    networks:
      - traefik_network

networks:
  traefik_network:
    name: traefik_network
    external: true
