services:
  jekyll-staging:
    image: "${DOCKERHUB_USERNAME}/${ARTIFACT_NAME}:${ENVIRONMENT}-latest"
    container_name: jekyll-staging
    restart: always
    environment:
      - "JEKYLL_ENV=${ENVIRONMENT}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jekyll-staging.rule=Host(`staging.${DOMAIN}`)"
      - "traefik.http.routers.jekyll-staging.entrypoints=web"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.jekyll-staging.middlewares=redirect-to-https"
      - "traefik.http.routers.jekyll-staging-ssl.rule=Host(`staging.${DOMAIN}`)"
      - "traefik.http.routers.jekyll-staging-ssl.entrypoints=websecure"
      - "traefik.http.routers.jekyll-staging-ssl.tls.certresolver=myresolver"
      - "traefik.http.services.jekyll-staging.loadbalancer.server.port=4000"
    networks:
      - traefik_network

networks:
  traefik_network:
    name: traefik_network
    external: true
