services:
  jekyll-local:
    build:
      context: ./jekyll
      dockerfile: Dockerfile
    container_name: jekyll-site
    volumes:
      - ./jekyll:/srv/jekyll
    env_file:
      - .env   
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jekyll.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.jekyll.entrypoints=web"
      - "traefik.http.services.jekyll.loadbalancer.server.port=4000"  
    networks:
      - traefik_network

  traefik-proxy:
    image: traefik:v2.10
    restart: always
    container_name: traefik-local
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
      - "8080:8080"  # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik/traefik.yml:/etc/traefik/traefik.yml"
    networks:
      - traefik_network

networks:
  traefik_network:
    driver: bridge
