services:
  website:
    image: ${DOCKERHUB_USERNAME}/${ARTIFACT_NAME}:latest
    container_name: ${ARTIFACT_NAME}
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf:/etc/letsencrypt/:ro
    environment:
      - DOMAIN=${DOMAIN}
    networks:
      - web
    depends_on:
      - certbot

  certbot:
    image: certbot/certbot:latest
    container_name: ${ARTIFACT_NAME}_certbot
    volumes:
      - ./certbot/www:/var/www/certbot/:rw
      - ./certbot/conf:/etc/letsencrypt/:rw
    command: certonly --webroot --webroot-path=/var/www/certbot --email ${ADMIN_EMAIL} --agree-tos --no-eff-email --force-renewal -d ${DOMAIN} -d www.${DOMAIN}
    networks:
      - web

networks:
  web:
    driver: bridge