api:
  dashboard: {{TRAEFIK_DASHBOARD}}
  insecure: {{TRAEFIK_INSECURE}}

ping: {}

log:
  level: INFO
  format: json

accessLog:
  format: json
  fields:
    headers:
      defaultMode: keep
      names:
        User-Agent: keep
        Authorization: drop
        Content-Type: keep

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: :443
    http:
      tls:
        certResolver: myresolver
        options: default

tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
  domains:
    - main: "{{DOMAIN}}"
      sans:
        - "*.{{DOMAIN}}"
        - "traefik.{{DOMAIN}}"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik_network
       
certificatesResolvers:
  myresolver:
    acme:
      caServer: "{{ACME_SERVER}}"
      email: "{{ACME_EMAIL}}"
      storage: "/acme.json"
      httpChallenge:
        entryPoint: "web"