api:
  dashboard: {{TRAEFIK_DASHBOARD}}
  insecure: {{TRAEFIK_INSECURE}}

ping: {}

entryPoints:
  web:
    address: ":{{WEB_PORT}}"

middlewares:
  block-probes:
    contentType:
      autoDetect: false
    headers:
      customResponseHeaders:
        X-Robots-Tag: "noindex, nofollow"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false