api:
  dashboard: {{TRAEFIK_DASHBOARD}}
  insecure: {{TRAEFIK_INSECURE}}

ping: {}

entryPoints:
  web:
    address: ":{{WEB_PORT}}"
  websecure:
    address: ":{{SECURE_PORT}}"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  myresolver:
    acme:
      caServer: "{{ACME_SERVER}}"
      email: "{{ACME_EMAIL}}"
      storage: "/acme.json"
      httpChallenge:
        entryPoint: "web"