name: Lint Commit Messages

on:
  pull_request:
    branches: [ master, develop ]
  push:
    branches: [ master, develop ]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Install commitlint
        run: |
          npm install -g @commitlint/cli @commitlint/config-conventional
      
      - name: Create commitlint config
        run: |
          echo "module.exports = {
            extends: ['@commitlint/config-conventional'],
            rules: {
              'type-enum': [
                2,
                'always',
                ['feat', 'fix', 'docs', 'style', 'refactor', 'test', 'chore']
              ],
              'header-max-length': [2, 'always', 100],
              'body-max-line-length': [0, 'always'],
              'footer-max-line-length': [0, 'always']
            }
          };" > commitlint.config.js
      
      - name: Validate commits
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            npx commitlint --from HEAD~1 --to HEAD --verbose
          else
            npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
          fi